list/urls.py
from django.urls import path

from list.views import (
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    task_completion
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("/create/", TaskCreateView.as_view(), name="task-create"),
    path("/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task_completion/<int:task_id>/", task_completion, name="task_completion"),
]

app_name = "list"

to_do_list/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("list.urls", namespace="list")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

list/models.py
from django.db import models
from django.utils import timezone


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    deadline = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["completed", "-created_at"]

    def __str__(self):
        return self.content

list/forms.py
from django import forms
from list.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"

list/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from list.forms import TaskForm
from list.models import Tag, Task


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5
    queryset = Tag.objects.all()


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("list:tag-list")


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 6


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("list:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("list:task-list")


def task_completion(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.completed = not task.completed
    task.save()
    return redirect("list:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To-do List</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="background-image"></div>

  <div class="container mt-4">
    <div class="row">
      <div class="col-md-3">
        {% include 'includes/sidebar.html' %}
      </div>
      <div class="col-md-9 content-container">
        <div class="content-animation">
          {% block content %}
          {% endblock %}
          {% include 'includes/pagination.html' %}
        </div>
      </div>
    </div>
  </div>

</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<div id="sidebar">
    <ul>
        <li><a href="{% url 'list:task-list' %}">Home</a></li>
        <li><a href="{% url 'list:tag-list' %}">Tag List</a></li>
    </ul>
</div>

templates/list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete the tag</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'list:tag-list' %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update the,Create a" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/tag_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'list:tag-create' %}" class="btn btn-primary link-to-page">
      Add new tag
    </a>
  </h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for tag in tag_list %}
          <tr>
            <td>{{ tag.name }}</td>
            <td><a href="{% url 'list:tag-update' tag.id %}" class="btn btn-update">Update</a></td>
            <td><a href="{% url 'list:tag-delete' tag.id %}" class="btn btn-delete">Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

templates/list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete the task</h1>
  <p>Are you sure that you want to delete this task?</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'list:task-list' %}" class="btn btn-primary">Cancel</a>
  </form>
{% endblock %}

templates/list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update the,Create a" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/list/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}To-Do List{% endblock %}

{% block content %}
    <h1>
      To-do List
    <a href="{% url 'list:task-create' %}" class="btn btn-primary">Add new task</a>
    </h1>
    <p>Welcome to the To-Do List. This is a simple app that allows you to create a list of tasks that you need to complete.</p>
    <div class="row mt-4">
    {% if task_list %}
      {% for task in task_list %}
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              {% for tag in task.tags.all %}
                <span class="badge badge-primary">{{ tag.name }}</span>
              {% endfor %}
              {% if task.completed %}
                  <a href="{% url 'list:task_completion' task.id %}" class="btn btn-warning float-right">Undo</a>
              {% else %}
                  <a href="{% url 'list:task_completion' task.id %}" class="btn btn-success float-right">Complete</a>
              {% endif %}
              <h5 class="card-title mt-2">{{ task.content }}</h5>
              <p>Created at: {{ task.created_at }}</p>
              <p><strong>Deadline: <span style="color: red;">{{ task.deadline }}</span></strong></p>
              <p><strong>Status: <span style="{% if task.completed %}color: green{% else %}color: orange{% endif %}">{% if task.completed %}Completed{% else %}Not completed{% endif %}</span></strong></p>

              <a href="{% url 'list:task-update' pk=task.id %}" class="btn btn-secondary btn-sm">Update</a>
              <a href="{% url 'list:task-delete' pk=task.id %}" class="btn btn-danger btn-sm">Delete</a>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div class="col-12">
        <p>There are nothing to do :) !</p>
      </div>
    {% endif %}
  </div>
{% endblock %}